<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Spider</title>
    <link rel="shortcut icon" type="image/x-icon" href="spider_logo.png" />
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body {
        margin: 50px 0 0 0;
        padding: 0;
        width: 100%;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        text-align: center;
        color: #aaa;
        background-color: #000000;
        font-size: 18px;
        }
        .btn{
            font-size: 22px;
            width:151px;
            padding:5px;
        }
        input{
            width:400px;
        }

    </style>

</head>
<body>
<img src="spider_logo.png" height="320" width="360"/>

<div class="mt-5"></div>

<form  method="post" id="form">
    <div class="container form-group">
        <input id="url" name="url" type="text" name="URL" placeholder="URL: https://google.com">
        <button id="start-btn" class="btn btn-primary rounded crawl-results">Start Crawl</button>
    </div>
</form>

<div class="mt-5"></div>

<div class="container-fluid">
        <table class="table table-striped table-dark table-hover">
            <thead>
                <tr>
                    <th scope="col">URL</th>
                    <th scope="col">Title</th>
                    <th scope="col">Number of Links</th>
                    <th scope="col">status Code</th>
                    <th scope="col">Body Text</th>
                </tr>
            </thead>

            <tbody>
            <?php foreach($data as $d):?>
                <tr>
                    <td> <?php echo $d->getUrl(); ?> </td>
                    <td> <?php echo $d->getTitle(); ?> </td>
                    <td> <?php echo $d->getNumOfLinks(); ?> </td>
                    <td> <?php echo $d->getStatusCode(); ?> </td>
                    <td> <?php echo $d->getBody(); ?> </td>
                </tr>

            <?php endforeach;?>   

            </tbody>
        </table>
</div>
</body>
</html>

<script type="text/javascript">
    // $('.crawl-results').on('click', function (e) {
    //     e.preventDefault();
    //     setInterval(fetchdata,5000);
    // });

    // function fetchdata(){
    //     $.ajax({
    //         url: '/ajaxCrawl',
    //         type: 'post',
    //         success: function(response){
    //             $('.ajax').html(response);
    //         },
    //         error: function(data){
    //             alert("error");
    //         }
    //     });
    // }

</script>
