<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Spider</title>
    <link rel="shortcut icon" type="image/x-icon" href="spider_logo.png" />
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <style>
        body {
        margin: 50px 0 0 0;
        padding: 0;
        width: 100%;
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        text-align: center;
        color: #aaa;
        background-color: #000000;
        font-size: 18px;
        }
        .btn{
            font-size: 22px;
            width:151px;
            padding:5px;
        }
        input{
            width:400px;
        }

    </style>

</head>
<body>
<img src="spider_logo.png" height="320" width="360"/>

<div class="mt-5"></div>

<form action="/" method="post">
    <div class="container form-group">
        <input id="url" name="url" type="text" name="URL" placeholder="URL">
        <button id="start-btn" class="btn btn-primary rounded ">Start Crawl</button>
    </div>
</form>

<div class="mt-5"></div>

</body>
</html>

<script type="text/javascript">
    document.getElementById("start-btn").onclick = function () {
        location.href = "/";
    };
</script>
